input {
  file {
    path => "/usr/share/logstash/ingest_data/application.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "tail"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp}  %{LOGLEVEL:level} %{NUMBER:pid} --- \[%{DATA:thread}\] %{DATA:logger}\s+: REPORT_INDEXED %{WORD:status} organization=%{DATA:organization} city=%{DATA:city} analyst=%{DATA:analyst} malware=%{DATA:malware} classification=%{GREEDYDATA:classification}"
    }
  }
  if "_grokparsefailure" in [tags] {
    drop { }
  }
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
  mutate {
    remove_field => ["message", "logger"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "forensic-logs-%{+YYYY.MM.dd}"
  }
  stdout {}
}